/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import battle.battleBl;
import data.Pokemon;
import javafx.scene.paint.Color;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class BattleField extends javax.swing.JFrame
{

    /**
     * Creates new form BattleField
     */
    
    private data.Pokemon ownTeam[];
    private battle.battleBl bl;
    
    private JLabel teamSlots[] = new JLabel[6];
    
    public BattleField()
    {
        initComponents();
    }

    public BattleField(Pokemon[] ownTeam)
    {
        initComponents();
        
        this.ownTeam = ownTeam;
        bl = new battle.battleBl(ownTeam);
        
        
        init();
    }
    
    private void init()
    {
        teamSlots[0] = lbSlot1;
        teamSlots[1] = lbSlot2;
        teamSlots[2] = lbSlot3;
        teamSlots[3] = lbSlot4;
        teamSlots[4] = lbSlot5;
        teamSlots[5] = lbSlot6;
        
        
        
        for(int i = 0; i < teamSlots.length; i++)
        {
            if(ownTeam[i] != null)
                teamSlots[i].setText(ownTeam[i].getName());
            teamSlots[i].setOpaque(true);
            teamSlots[i].setBackground(java.awt.Color.green);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        plTeamPriview = new javax.swing.JPanel();
        lbSlot1 = new javax.swing.JLabel();
        lbSlot2 = new javax.swing.JLabel();
        lbSlot3 = new javax.swing.JLabel();
        lbSlot4 = new javax.swing.JLabel();
        lbSlot5 = new javax.swing.JLabel();
        lbSlot6 = new javax.swing.JLabel();
        lbMyPokemon = new javax.swing.JLabel();
        lbEnemyPokemon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbMove1 = new javax.swing.JLabel();
        lbMove2 = new javax.swing.JLabel();
        lbMove3 = new javax.swing.JLabel();
        lbMove4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbESlot1 = new javax.swing.JLabel();
        lbESlot2 = new javax.swing.JLabel();
        lbESlot3 = new javax.swing.JLabel();
        lbESlot4 = new javax.swing.JLabel();
        lbESlot5 = new javax.swing.JLabel();
        lbESlot6 = new javax.swing.JLabel();
        pbMyHP = new javax.swing.JProgressBar();
        pbEnemyHP = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        plTeamPriview.setMinimumSize(new java.awt.Dimension(215, 600));
        plTeamPriview.setLayout(new java.awt.GridLayout(6, 0));

        lbSlot1.setText("jLabel1");
        plTeamPriview.add(lbSlot1);

        lbSlot2.setText("jLabel1");
        plTeamPriview.add(lbSlot2);

        lbSlot3.setText("jLabel1");
        plTeamPriview.add(lbSlot3);

        lbSlot4.setText("jLabel1");
        plTeamPriview.add(lbSlot4);

        lbSlot5.setText("jLabel1");
        plTeamPriview.add(lbSlot5);

        lbSlot6.setText("jLabel1");
        plTeamPriview.add(lbSlot6);

        lbMyPokemon.setBackground(new java.awt.Color(153, 255, 204));
        lbMyPokemon.setText("jLabel7");
        lbMyPokemon.setOpaque(true);

        lbEnemyPokemon.setBackground(new java.awt.Color(153, 255, 204));
        lbEnemyPokemon.setText("jLabel7");
        lbEnemyPokemon.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(485, 115));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        lbMove1.setText("jLabel9");
        jPanel1.add(lbMove1);

        lbMove2.setText("jLabel9");
        jPanel1.add(lbMove2);

        lbMove3.setText("jLabel9");
        jPanel1.add(lbMove3);

        lbMove4.setText("jLabel9");
        jPanel1.add(lbMove4);

        jPanel2.setLayout(new java.awt.GridLayout(1, 6));

        lbESlot1.setText("jLabel13");
        jPanel2.add(lbESlot1);

        lbESlot2.setText("jLabel13");
        jPanel2.add(lbESlot2);

        lbESlot3.setText("jLabel13");
        jPanel2.add(lbESlot3);

        lbESlot4.setText("jLabel13");
        jPanel2.add(lbESlot4);

        lbESlot5.setText("jLabel13");
        jPanel2.add(lbESlot5);

        lbESlot6.setText("jLabel13");
        jPanel2.add(lbESlot6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plTeamPriview, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbMyHP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pbEnemyHP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbEnemyPokemon, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plTeamPriview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnemyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pbEnemyHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(pbMyHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMyPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BattleField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BattleField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbESlot1;
    private javax.swing.JLabel lbESlot2;
    private javax.swing.JLabel lbESlot3;
    private javax.swing.JLabel lbESlot4;
    private javax.swing.JLabel lbESlot5;
    private javax.swing.JLabel lbESlot6;
    private javax.swing.JLabel lbEnemyPokemon;
    private javax.swing.JLabel lbMove1;
    private javax.swing.JLabel lbMove2;
    private javax.swing.JLabel lbMove3;
    private javax.swing.JLabel lbMove4;
    private javax.swing.JLabel lbMyPokemon;
    private javax.swing.JLabel lbSlot1;
    private javax.swing.JLabel lbSlot2;
    private javax.swing.JLabel lbSlot3;
    private javax.swing.JLabel lbSlot4;
    private javax.swing.JLabel lbSlot5;
    private javax.swing.JLabel lbSlot6;
    private javax.swing.JProgressBar pbEnemyHP;
    private javax.swing.JProgressBar pbMyHP;
    private javax.swing.JPanel plTeamPriview;
    // End of variables declaration//GEN-END:variables
}
