/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author User
 */
public class Team extends javax.swing.JFrame
{

    /**
     * Creates new form Team
     */
    public Team()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbSlot1 = new javax.swing.JLabel();
        lbSlot2 = new javax.swing.JLabel();
        lbSlot3 = new javax.swing.JLabel();
        lbSlot4 = new javax.swing.JLabel();
        lbSlot5 = new javax.swing.JLabel();
        lbSlot6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 750));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        lbSlot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot1.setText("empty");
        lbSlot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot1);

        lbSlot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot2.setText("empty");
        lbSlot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot2);

        lbSlot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot3.setText("empty");
        lbSlot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot3);

        lbSlot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot4.setText("empty");
        lbSlot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot4);

        lbSlot5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot5.setText("empty");
        lbSlot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot5);

        lbSlot6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot6.setText("empty");
        lbSlot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbSlot6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Team().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbSlot1;
    private javax.swing.JLabel lbSlot2;
    private javax.swing.JLabel lbSlot3;
    private javax.swing.JLabel lbSlot4;
    private javax.swing.JLabel lbSlot5;
    private javax.swing.JLabel lbSlot6;
    // End of variables declaration//GEN-END:variables
}
