/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Team extends javax.swing.JFrame
{

    /**
     * Creates new form Team
     */
    private data.Pokemon team[] = new data.Pokemon[6];
    private JLabel slots[] = new JLabel[6];
    
    public Team()
    {
        initComponents();
        for(int i = 0; i < team.length; i++)
            team[i] = null;
        
        slots[0] = lbSlot1;
        slots[1] = lbSlot2;
        slots[2] = lbSlot3;
        slots[3] = lbSlot4;
        slots[4] = lbSlot5;
        slots[5] = lbSlot6;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btStartBattle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbSlot1 = new javax.swing.JLabel();
        lbSlot2 = new javax.swing.JLabel();
        lbSlot3 = new javax.swing.JLabel();
        lbSlot4 = new javax.swing.JLabel();
        lbSlot5 = new javax.swing.JLabel();
        lbSlot6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 750));
        setPreferredSize(new java.awt.Dimension(350, 750));

        btStartBattle.setText("Start Battle");
        btStartBattle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btStartBattleActionPerformed(evt);
            }
        });
        getContentPane().add(btStartBattle, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        lbSlot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot1.setText("empty");
        lbSlot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick1(evt);
            }
        });
        jPanel1.add(lbSlot1);

        lbSlot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot2.setText("empty");
        lbSlot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick2(evt);
            }
        });
        jPanel1.add(lbSlot2);

        lbSlot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot3.setText("empty");
        lbSlot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick3(evt);
            }
        });
        jPanel1.add(lbSlot3);

        lbSlot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot4.setText("empty");
        lbSlot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick4(evt);
            }
        });
        jPanel1.add(lbSlot4);

        lbSlot5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot5.setText("empty");
        lbSlot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick5(evt);
            }
        });
        jPanel1.add(lbSlot5);

        lbSlot6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot6.setText("empty");
        lbSlot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSlot6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                onClick6(evt);
            }
        });
        jPanel1.add(lbSlot6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void onClick1(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick1
    {//GEN-HEADEREND:event_onClick1
        changePokemon(0);
    }//GEN-LAST:event_onClick1

    private void onClick2(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick2
    {//GEN-HEADEREND:event_onClick2
        changePokemon(1);
    }//GEN-LAST:event_onClick2

    private void onClick3(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick3
    {//GEN-HEADEREND:event_onClick3
        changePokemon(2);
    }//GEN-LAST:event_onClick3

    private void onClick4(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick4
    {//GEN-HEADEREND:event_onClick4
        changePokemon(3);
    }//GEN-LAST:event_onClick4

    private void onClick5(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick5
    {//GEN-HEADEREND:event_onClick5
        changePokemon(4);
    }//GEN-LAST:event_onClick5

    private void onClick6(java.awt.event.MouseEvent evt)//GEN-FIRST:event_onClick6
    {//GEN-HEADEREND:event_onClick6
        changePokemon(5);
    }//GEN-LAST:event_onClick6

    private void btStartBattleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btStartBattleActionPerformed
    {//GEN-HEADEREND:event_btStartBattleActionPerformed
        BattleField bf = new BattleField(team);
        bf.setVisible(true);
    }//GEN-LAST:event_btStartBattleActionPerformed

    public void changePokemon(int slot)
    {
        gui.PokeEditor pEdit = null;
        if(team[slot] == null)
            pEdit =  new gui.PokeEditor(this, true);
        else
            pEdit =  new gui.PokeEditor(this, true, team[slot]); 
        
        pEdit.setVisible(true);
        
        if(pEdit.isOkay())
        {
            team[slot] = pEdit.getPokemon();
            slots[slot].setText(pEdit.getPokemon().getName());
            System.out.println("change");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Team().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStartBattle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSlot1;
    private javax.swing.JLabel lbSlot2;
    private javax.swing.JLabel lbSlot3;
    private javax.swing.JLabel lbSlot4;
    private javax.swing.JLabel lbSlot5;
    private javax.swing.JLabel lbSlot6;
    // End of variables declaration//GEN-END:variables
}
